from fastapi import FastAPI
from sqlalchemy import text

from core import models  # noqa: F401
from core.config import settings
from core.db import Base, engine
from core.logging_journal import configure_logging, journal_event
from core.routers.workspace import initialize_workspace_monitoring_runtime, shutdown_workspace_monitoring_runtime
from core.routers import api_router

configure_logging()

app = FastAPI(title=settings.app_name, version=settings.app_version)
app.include_router(api_router)


@app.on_event("startup")
async def ensure_schema() -> None:
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
        await conn.execute(text("ALTER TABLE IF EXISTS routing_execution_metrics ADD COLUMN IF NOT EXISTS policy_version VARCHAR(80) DEFAULT 'routing-policy-v1'"))
        await conn.execute(text("ALTER TABLE IF EXISTS routing_execution_metrics ADD COLUMN IF NOT EXISTS engine_version VARCHAR(120) DEFAULT 'unknown'"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS expected_state_delta JSON DEFAULT '{}'::json"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS validation_method VARCHAR(120) DEFAULT 'hint'"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS sequence_index INTEGER DEFAULT 1"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS depends_on_action_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS parent_action_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS retry_of_action_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS replaced_action_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS replacement_action_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS recovery_classification VARCHAR(40) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS actions ADD COLUMN IF NOT EXISTS chain_event VARCHAR(40) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS input_event_resolutions ADD COLUMN IF NOT EXISTS confidence_tier VARCHAR(20) DEFAULT 'unknown'"))
        await conn.execute(text("ALTER TABLE IF EXISTS input_event_resolutions ADD COLUMN IF NOT EXISTS outcome VARCHAR(40) DEFAULT 'requires_confirmation'"))
        await conn.execute(text("ALTER TABLE IF EXISTS input_event_resolutions ADD COLUMN IF NOT EXISTS clarification_prompt TEXT DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS input_event_resolutions ADD COLUMN IF NOT EXISTS escalation_reasons JSONB DEFAULT '[]'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS resolution_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS goal_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS arguments_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS safety_mode VARCHAR(40) DEFAULT 'standard'"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS requested_executor VARCHAR(120) DEFAULT 'tod'"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS dispatch_decision VARCHAR(40) DEFAULT 'requires_confirmation'"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS status VARCHAR(40) DEFAULT 'pending'"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS reason TEXT DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS capability_executions ADD COLUMN IF NOT EXISTS feedback_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS motion_plan_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS simulation_outcome VARCHAR(80) DEFAULT 'not_run'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS simulation_status VARCHAR(40) DEFAULT 'not_run'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS simulation_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS simulation_gate_passed BOOLEAN DEFAULT false"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS execution_capability VARCHAR(120) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS execution_status VARCHAR(40) DEFAULT 'not_started'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS execution_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS execution_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS abort_status VARCHAR(40) DEFAULT 'not_aborted'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_action_plans ADD COLUMN IF NOT EXISTS abort_reason TEXT DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS desired_running BOOLEAN DEFAULT false"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS runtime_status VARCHAR(40) DEFAULT 'stopped'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS scan_trigger_mode VARCHAR(40) DEFAULT 'interval'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS interval_seconds INTEGER DEFAULT 30"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS freshness_threshold_seconds INTEGER DEFAULT 900"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS cooldown_seconds INTEGER DEFAULT 10"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS max_scan_rate INTEGER DEFAULT 6"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS priority_zones JSONB DEFAULT '[]'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS last_scan_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS scan_count INTEGER DEFAULT 0"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS last_scan_reason VARCHAR(120) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS last_deltas_json JSONB DEFAULT '[]'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS last_proposal_ids JSONB DEFAULT '[]'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS last_snapshot_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS last_started_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS last_stopped_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_monitoring_states ADD COLUMN IF NOT EXISTS metadata_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS step_policy_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS stop_on_failure BOOLEAN DEFAULT true"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS cooldown_seconds INTEGER DEFAULT 0"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS requires_approval BOOLEAN DEFAULT true"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS approved_by VARCHAR(120) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS last_advanced_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_autonomous_chains ADD COLUMN IF NOT EXISTS audit_trail_json JSONB DEFAULT '[]'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS execution_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS action_plan_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS chain_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS interruption_type VARCHAR(80) DEFAULT 'operator_pause'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS source VARCHAR(80) DEFAULT 'operator'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS requested_outcome VARCHAR(40) DEFAULT 'require_operator_decision'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS applied_outcome VARCHAR(40) DEFAULT 'require_operator_decision'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS status VARCHAR(40) DEFAULT 'active'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS reason TEXT DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS actor VARCHAR(120) DEFAULT 'workspace'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS resolved_by VARCHAR(120) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_interruption_events ADD COLUMN IF NOT EXISTS metadata_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS execution_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS action_plan_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS chain_id INTEGER"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS signal_type VARCHAR(80) DEFAULT 'zone_state_changed'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS predicted_outcome VARCHAR(60) DEFAULT 'continue_monitor'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION DEFAULT 0.0"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS source VARCHAR(80) DEFAULT 'predictive_monitor'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS status VARCHAR(40) DEFAULT 'active'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS reason TEXT DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS actor VARCHAR(120) DEFAULT 'workspace'"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS resolved_by VARCHAR(120) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_replan_signals ADD COLUMN IF NOT EXISTS metadata_json JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_proposals ADD COLUMN IF NOT EXISTS priority_score DOUBLE PRECISION DEFAULT 0.0"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_proposals ADD COLUMN IF NOT EXISTS priority_reason TEXT DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS user_preferences ADD COLUMN IF NOT EXISTS user_id VARCHAR(120) DEFAULT 'operator'"))
        await conn.execute(text("ALTER TABLE IF EXISTS user_preferences ADD COLUMN IF NOT EXISTS preference_type VARCHAR(120) DEFAULT ''"))
        await conn.execute(text("ALTER TABLE IF EXISTS user_preferences ADD COLUMN IF NOT EXISTS value JSONB DEFAULT '{}'::jsonb"))
        await conn.execute(text("ALTER TABLE IF EXISTS user_preferences ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION DEFAULT 0.0"))
        await conn.execute(text("ALTER TABLE IF EXISTS user_preferences ADD COLUMN IF NOT EXISTS source VARCHAR(80) DEFAULT 'manual'"))
        await conn.execute(text("ALTER TABLE IF EXISTS user_preferences ADD COLUMN IF NOT EXISTS last_updated TIMESTAMPTZ DEFAULT now()"))
        await conn.execute(text("ALTER TABLE IF EXISTS constraint_evaluations ADD COLUMN IF NOT EXISTS outcome_result VARCHAR(40) DEFAULT 'unknown'"))
        await conn.execute(text("ALTER TABLE IF EXISTS constraint_evaluations ADD COLUMN IF NOT EXISTS outcome_quality DOUBLE PRECISION DEFAULT 0.0"))
        await conn.execute(text("ALTER TABLE IF EXISTS constraint_evaluations ADD COLUMN IF NOT EXISTS outcome_recorded_at TIMESTAMPTZ"))
        await conn.execute(text("ALTER TABLE IF EXISTS workspace_decision_records ADD COLUMN IF NOT EXISTS result_quality DOUBLE PRECISION DEFAULT 0.0"))

    await initialize_workspace_monitoring_runtime()


@app.on_event("shutdown")
async def on_shutdown() -> None:
    await shutdown_workspace_monitoring_runtime()


@app.get("/")
def root():
    journal_event(actor="system", action="root", result="ok")
    return {"status": "MIM core online"}
