from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path
import subprocess

from core.config import PROJECT_ROOT, settings

CONTRACT_VERSION = "tod-mim-shared-contract-v1"
MANIFEST_VERSION = "1"
SCHEMA_VERSION = "2026-03-12-66"

SIGNATURE_FILES = [
    "core/models.py",
    "core/schemas.py",
    "core/routers/__init__.py",
    "core/routers/gateway.py",
    "core/vision_policy.py",
    "core/voice_policy.py",
    "core/routers/manifest.py",
    "core/config.py",
    "core/manifest.py",
    "core/horizon_planning.py",
    "core/horizon_planning_service.py",
    "core/routers/horizon_planning.py",
    "core/environment_strategy_service.py",
    "core/decision_record_service.py",
    "core/improvement_service.py",
    "core/policy_experiment_service.py",
    "core/maintenance_service.py",
    "core/routers/environment_strategy.py",
    "core/routers/decision_records.py",
    "core/routers/improvement.py",
    "core/routers/reasoning.py",
    "core/routers/policy_experiments.py",
    "core/routers/maintenance.py",
    "core/improvement_recommendation_service.py",
    "core/improvement_governance_service.py",
    "core/cross_domain_reasoning_service.py",
    "core/goal_strategy_service.py",
    "core/inquiry_service.py",
    "core/orchestration_service.py",
    "core/state_bus_service.py",
    "core/state_bus_consumer_service.py",
    "core/autonomy_boundary_service.py",
    "core/stewardship_service.py",
    "core/routers/autonomy_boundaries.py",
    "core/routers/strategy.py",
    "core/routers/inquiry.py",
    "core/routers/orchestration.py",
    "core/routers/state_bus.py",
    "core/routers/stewardship.py",
    "docs/tod-mim-bridge.md",
    "docs/objective-21-unified-input-gateway.md",
    "docs/objective-22-mim-tod-execution-feedback-integration.md",
    "docs/objective-23-operator-control-and-exception-handling.md",
    "docs/objective-23b-safe-capability-expansion.md",
    "docs/objective-24-workspace-observation-memory.md",
    "docs/objective-25-memory-informed-routing.md",
    "docs/objective-26-object-identity-persistence.md",
    "docs/objective-27-workspace-map-and-relational-context.md",
    "docs/objective-28-autonomous-task-proposals.md",
    "docs/objective-29-directed-targeting.md",
    "docs/objective-30-safe-directed-action-planning.md",
    "docs/objective-31-safe-reach-approach-simulation.md",
    "docs/objective-32-safe-reach-execution.md",
    "docs/objective-33-autonomous-execution-proposals.md",
    "docs/objective-34-continuous-workspace-monitoring-loop.md",
    "docs/objective-35-autonomous-task-execution-policies.md",
    "docs/objective-36-multi-step-autonomous-task-chaining.md",
    "docs/objective-37-human-aware-interruption-and-safe-pause-handling.md",
    "docs/objective-38-predictive-workspace-change-and-replanning.md",
    "docs/objective-39-policy-based-autonomous-priority-selection.md",
    "docs/objective-40-human-preference-and-routine-memory.md",
    "docs/objective-41-closed-loop-autonomous-task-execution.md",
    "docs/objective-42-multi-capability-coordination.md",
    "docs/objective-43-human-aware-workspace-behavior.md",
    "docs/objective-44-constraint-evaluation-engine.md",
    "docs/objective-45-constraint-weight-learning.md",
    "docs/objective-45-promotion-readiness-report.md",
    "docs/objective-45-prod-promotion-report.md",
    "docs/mim-core-charter.md",
    "docs/objective-46-long-horizon-planning.md",
    "docs/objective-46-promotion-readiness-report.md",
    "docs/objective-46-prod-promotion-report.md",
    "docs/objective-47-environment-strategy-formation.md",
    "docs/objective-47-promotion-readiness-report.md",
    "docs/objective-47-prod-promotion-report.md",
    "docs/objective-48-human-preference-strategy-integration.md",
    "docs/objective-48-promotion-readiness-report.md",
    "docs/objective-48-prod-promotion-report.md",
    "docs/objective-49-self-improvement-proposal-engine.md",
    "docs/objective-49-promotion-readiness-report.md",
    "docs/objective-49-prod-promotion-report.md",
    "docs/objective-50-environment-maintenance-autonomy.md",
    "docs/objective-50-promotion-readiness-report.md",
    "docs/objective-50-prod-promotion-report.md",
    "docs/objective-51-policy-experiment-sandbox.md",
    "docs/objective-51-promotion-readiness-report.md",
    "docs/objective-51-prod-promotion-report.md",
    "docs/objective-52-concept-and-pattern-memory.md",
    "docs/objective-52-promotion-readiness-report.md",
    "docs/objective-52-prod-promotion-report.md",
    "core/routers/workspace.py",
    "core/routers/constraints.py",
    "core/routers/constraint_learning.py",
    "core/constraint_engine.py",
    "core/constraint_service.py",
    "core/constraint_learning.py",
    "core/constraint_learning_service.py",
    "core/concept_memory_service.py",
    "core/development_memory_service.py",
    "core/routers/preferences.py",
    "core/preferences.py",
    "docs/objective-53-multi-session-developmental-memory.md",
    "docs/objective-53-promotion-readiness-report.md",
    "docs/objective-53-prod-promotion-report.md",
    "docs/objective-54-self-guided-improvement-loop.md",
    "docs/objective-54-promotion-readiness-report.md",
    "docs/objective-55-improvement-prioritization-and-governance.md",
    "docs/objective-55-promotion-readiness-report.md",
    "docs/objective-56-cross-domain-reasoning.md",
    "docs/objective-56-promotion-readiness-report.md",
    "docs/objective-57-goal-strategy-engine.md",
    "docs/objective-57-promotion-readiness-report.md",
    "docs/objective-57-prod-promotion-report.md",
    "docs/objective-58-adaptive-autonomy-boundaries.md",
    "docs/objective-58-promotion-readiness-report.md",
    "docs/objective-58-prod-promotion-report.md",
    "docs/objective-59-strategic-goal-persistence-review.md",
    "docs/objective-59-promotion-readiness-report.md",
    "docs/objective-60-environment-stewardship-loop.md",
    "docs/objective-60-promotion-readiness-report.md",
    "docs/objective-61-live-perception-adapters.md",
    "docs/objective-61-promotion-readiness-report.md",
    "docs/objective-61_1-regression-recovery-baseline-stabilization.md",
    "docs/objective-61_1-promotion-readiness-report.md",
    "docs/objective-61_1-prod-promotion-report.md",
    "docs/objective-62-inquisitive-question-loop.md",
    "docs/objective-62-promotion-readiness-report.md",
    "docs/objective-62-prod-promotion-report.md",
    "docs/objective-63-cross-domain-task-orchestration.md",
    "docs/objective-63-promotion-readiness-report.md",
    "docs/objective-63-prod-promotion-report.md",
    "docs/objective-64-human-aware-cross-domain-collaboration.md",
    "docs/objective-64-promotion-readiness-report.md",
    "docs/objective-64-prod-promotion-report.md",
    "docs/objective-65-human-aware-collaboration-negotiation.md",
    "docs/objective-65-promotion-readiness-report.md",
    "docs/objective-65-prod-promotion-report.md",
    "docs/objective-66-negotiated-task-resolution-follow-through.md",
    "docs/objective-67-negotiation-memory-and-human-preference-consolidation.md",
    "docs/objective-68-negotiation-memory-decay-and-contextualization.md",
    "docs/objective-69-negotiation-pattern-abstraction.md",
    "docs/objective-70-collaboration-strategy-profiles.md",
    "docs/objective-71-unified-state-bus.md",
    "docs/objective-72-state-bus-consumers-and-cross-system-subscription.md",
    "docs/objective-73-bus-driven-cross-system-reactions.md",
    "config/vision_policy.json",
    "config/voice_policy.json",
]

CAPABILITIES = [
    "health",
    "status",
    "manifest",
    "objectives",
    "tasks",
    "results",
    "reviews",
    "journal",
    "routing_history",
    "routing_engines",
    "routing_stats",
    "routing_engine_detail",
    "routing_task_stats",
    "goals",
    "actions",
    "custody_chain",
    "goal_plans",
    "goal_timeline",
    "goal_status",
    "goal_recovery",
    "unified_input_gateway",
    "speech_output",
    "speech_input_adapter",
    "vision_observation_adapter",
    "capability_registry",
    "capability_to_goal_bridge",
    "event_resolution",
    "vision_confidence_policy",
    "voice_confidence_policy",
    "speech_output_execution",
    "capability_execution_binding",
    "execution_feedback_updater",
    "execution_handoff_contract",
    "tod_feedback_publisher",
    "execution_feedback_auth_boundary",
    "operator_execution_inbox",
    "operator_execution_actions",
    "operator_exception_normalization",
    "workspace_scan_capability",
    "operator_observation_review",
    "workspace_observation_memory",
    "workspace_observation_query_api",
    "memory_informed_routing",
    "object_identity_persistence",
    "workspace_map_relational_context",
    "autonomous_workspace_task_proposals",
    "directed_workspace_targeting",
    "safe_directed_action_planning",
    "safe_reach_approach_simulation",
    "safe_reach_execution",
    "autonomous_execution_proposals",
    "continuous_workspace_monitoring_loop",
    "autonomous_task_execution_policies",
    "multi_step_autonomous_task_chaining",
    "human_aware_interruption_pause_handling",
    "predictive_workspace_change_replanning",
    "policy_based_autonomous_priority_selection",
    "human_preference_and_routine_memory",
    "closed_loop_autonomous_task_execution",
    "multi_capability_coordination",
    "human_aware_workspace_behavior",
    "constraint_evaluation_engine",
    "constraint_weight_learning",
    "long_horizon_planning",
    "environment_strategy_formation",
    "human_preference_strategy_integration",
    "decision_record_trace",
    "self_improvement_proposal_engine",
    "environment_maintenance_autonomy",
    "policy_experiment_sandbox",
    "concept_pattern_memory",
    "multi_session_developmental_memory",
    "self_guided_improvement_loop",
    "improvement_prioritization_governance",
    "cross_domain_reasoning",
    "goal_strategy_engine",
    "adaptive_autonomy_boundaries",
    "strategic_goal_persistence_review",
    "environment_stewardship_loop",
    "live_perception_adapters",
    "inquisitive_question_loop",
    "cross_domain_task_orchestration",
    "human_aware_cross_domain_collaboration",
    "human_aware_collaboration_negotiation",
    "negotiated_task_resolution_follow_through",
    "negotiation_memory_human_preference_consolidation",
    "negotiation_memory_decay_contextualization",
    "negotiation_pattern_abstraction",
    "collaboration_strategy_profiles",
    "unified_state_bus",
    "state_bus_consumers_cross_system_subscription",
    "bus_driven_cross_system_reactions",
]

RECENT_CHANGES = [
    "Added review endpoint",
    "Added journal endpoint",
    "Aligned structured workflow schema",
    "Added manifest endpoint and metadata",
    "Added goal/action/state/validation custody chain",
    "Added multi-step goal execution planning and timeline/status endpoints",
    "Added retry/skip/replace/resume recovery operations for goal chains",
    "Added Objective 21 unified input gateway and adapters",
    "Added Objective 21.2 capability-to-goal bridge with safety gating and inspectability",
    "Added Objective 21.3 vision observation confidence policy tiers and escalation outcomes",
    "Added runtime vision policy inspection endpoint",
    "Added Objective 21.4 voice interaction policy and structured speech output execution",
    "Added Objective 21.5 capability execution binding and dispatch inspectability",
    "Added Objective 21.7 guarded execution feedback updater",
    "Added Objective 22 MIM↔TOD execution handoff contract and feedback integration",
    "Added Objective 23 operator control surface and exception handling endpoints",
    "Added Objective 23B safe capability expansion for workspace_scan",
    "Added Objective 24 workspace observation memory with dedupe, aging, and query endpoints",
    "Added Objective 25 memory-informed routing from workspace observation memory",
    "Added Objective 26 object identity persistence with matching and moved/missing logic",
    "Added Objective 27 workspace map and relational context with spatial routing hints",
    "Added Objective 28 autonomous workspace-state task proposals and operator review actions",
    "Added Objective 29 directed workspace target resolution with confidence policy and confirmation",
    "Added Objective 30 safe directed action planning with operator approval and queue handoff",
    "Added Objective 31 safe reach/approach simulation with collision policy and queue gating",
    "Added Objective 32 safe reach execution with precondition gating and abort controls",
    "Added Objective 33 autonomous execution proposals with policy endpoints and operator acceptance",
    "Added Objective 34 continuous workspace monitoring loop with delta-driven proposal triggers",
    "Added Objective 35 autonomous task execution policies with safety-throttled auto-execution and operator overrides",
    "Added Objective 36 policy-controlled multi-step autonomous task chaining with approval/cooldown/failure controls and chain audit trail",
    "Added Objective 37 human-aware interruption events with policy-driven pause/stop/resume controls and safety-validated resume gating",
    "Added Objective 38 predictive workspace-change signaling and preemptive action-plan replanning workflow",
    "Added Objective 39 policy-based autonomous proposal priority scoring and next-proposal scheduler endpoint",
    "Added Objective 40 human preference and routine memory with preference APIs and policy integration",
    "Added Objective 41 closed-loop autonomous controller with policy outcomes, safety throttle expansion, interruption-aware pausing, and result verification audit",
    "Added Objective 42 safe multi-capability chain coordination with dependency policy, step verification, stop-on-failure escalation, and explainable chain audit trail",
    "Added Objective 43 human-aware workspace behavior signals and policy gating for shared-workspace pause/confirm/replan decisions with inspectable state",
    "Added Objective 44 centralized constraint evaluation engine with structured decision outcomes, explanation metadata, and reusable integration hooks",
    "Added Objective 45 proposal-only constraint weight learning loop with outcome recording, rolling success stats, and auditable soft adjustment proposals",
    "Added Objective 46 long-horizon multi-goal planning with future-state scoring, checkpointed execution states, and replan-on-drift inspectability",
    "Added Objective 47 environment strategy formation with persistent strategy lifecycle, strategy-driven horizon weighting, and strategy inspectability APIs",
    "Added Objective 48 preference-aware strategy integration with routine pattern strategy generation and unified decision record reasoning trace",
    "Added Objective 49 self-improvement proposal engine with rule-based friction pattern detection and review-gated improvement artifacts",
    "Added Objective 50 proactive environment maintenance autonomy with degraded-state detection, auto maintenance strategies, and bounded corrective execution audit trail",
    "Added Objective 51 policy experiment sandbox with bounded soft-policy trial runs, baseline-vs-experiment comparison, and promote/reject/revise recommendations",
    "Added Objective 52 concept and pattern memory with rule-based concept extraction, inspectable concept records, and concept-influenced strategy weighting",
    "Added Objective 53 multi-session developmental memory with cross-session pattern aggregation, inspectable development patterns, and self-improvement feedback influence",
    "Added Objective 54 self-guided improvement loop with pattern-triggered proposals, sandbox orchestration, standardized experiment metrics, and review-gated recommendations",
    "Added Objective 55 improvement prioritization and governance with weighted backlog scoring, lifecycle state orchestration, and operator-visible ranking/risk reasoning",
    "Added Objective 56 cross-domain reasoning with unified workspace, communication, external-information, and developmental-memory context aggregation",
    "Added Objective 57 goal strategy engine with strategic goal synthesis, deterministic ranking, and strategy-to-plan bridge generation",
    "Added Objective 58 adaptive autonomy boundaries with experience-conditioned policy recommendations and applyable autonomy limits",
    "Added Objective 59 strategic goal persistence and review with cross-session carry-forward scoring and operator review audit",
    "Added Objective 60 environment stewardship loop with desired-state maintenance, integrated strategy-memory-autonomy inputs, and inspectable cycle history",
    "Added Objective 61 live perception adapters with camera/mic source ingestion, throttling, source health tracking, and inspectable adapter status",
    "Added Objective 61.1 regression recovery stabilization by restoring Objective 49/51 idempotent proposal generation behavior and re-establishing full green integration baseline",
    "Added Objective 62 inquisitive question loop with uncertainty-triggered inquiry generation, explainable question state, and answer-driven downstream planning effects",
    "Added Objective 63 cross-domain task orchestration with dependency-aware coordination paths, inspectable orchestration state, and downstream artifact linking",
    "Added Objective 64 human-aware cross-domain collaboration with collaboration-mode policy, communication-aware task shaping, and explainable human-context modifiers",
    "Added Objective 65 human-aware collaboration negotiation with persistent negotiation state, structured option shaping, response endpoints, and safe unanswered fallbacks",
    "Added Objective 66 negotiated task resolution follow-through with negotiation outcome memory, pattern-based reuse, and downstream follow-through propagation",
    "Added Objective 67 negotiation memory and human-preference consolidation with durable preference conversion, inspectable evidence, and safe revision behavior",
    "Added Objective 68 negotiation-memory decay and contextualization with freshness-aware confidence decay, context-scoped preference keys, and stale-pattern suppression",
    "Added Objective 69 negotiation pattern abstraction with persistent collaboration concepts, rule-based extraction, bounded influence defaults, and inspectable pattern APIs",
    "Added Objective 70 collaboration strategy profiles with synthesized collaboration modes, bounded profile influence, and inspectable profile recompute APIs",
    "Added Objective 71 unified state bus with durable snapshot/event-stream separation, multi-domain event ingestion, and inspectable state-bus APIs",
    "Added Objective 72 state bus consumers with filtered subscriptions, idempotent acknowledgment, replay controls, and mim-core cross-system consumption",
    "Added Objective 73 bus-driven cross-system reactions with reaction consumer step, derived reaction events, and replay-safe idempotent handling",
]


def _signature_input() -> str:
    blocks: list[str] = [
        f"contract_version={CONTRACT_VERSION}",
        f"schema_version={SCHEMA_VERSION}",
    ]

    for rel_path in SIGNATURE_FILES:
        file_path = PROJECT_ROOT / rel_path
        if file_path.exists():
            content_hash = sha256(file_path.read_bytes()).hexdigest()
            blocks.append(f"{rel_path}:{content_hash}")
        else:
            blocks.append(f"{rel_path}:missing")

    return "\n".join(blocks)


def _last_updated_at() -> datetime:
    timestamps: list[float] = []
    for rel_path in SIGNATURE_FILES:
        file_path = PROJECT_ROOT / rel_path
        if file_path.exists():
            timestamps.append(file_path.stat().st_mtime)

    if not timestamps:
        return datetime.now(timezone.utc)

    return datetime.fromtimestamp(max(timestamps), tz=timezone.utc)


def build_repo_signature() -> str:
    seed = _signature_input()
    return f"sha256:{sha256(seed.encode('utf-8')).hexdigest()}"


def _resolve_git_sha() -> str:
    if settings.build_git_sha and settings.build_git_sha != "unknown":
        return settings.build_git_sha

    try:
        result = subprocess.run(
            ["git", "-C", str(PROJECT_ROOT), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"


def build_manifest() -> dict:
    return {
        "system_name": "MIM",
        "system_version": settings.app_version,
        "manifest_version": MANIFEST_VERSION,
        "contract_version": CONTRACT_VERSION,
        "schema_version": SCHEMA_VERSION,
        "app_name": settings.app_name,
        "app_version": settings.app_version,
        "environment": settings.environment,
        "release_tag": settings.release_tag,
        "config_profile": settings.config_profile,
        "git_sha": _resolve_git_sha(),
        "build_timestamp": settings.build_timestamp,
        "repo_signature": build_repo_signature(),
        "capabilities": CAPABILITIES,
        "recent_changes": RECENT_CHANGES,
        "last_updated_at": _last_updated_at(),
        "generated_at": datetime.now(timezone.utc),
        "endpoints": [
            "/health",
            "/status",
            "/manifest",
            "/objectives",
            "/tasks",
            "/results",
            "/reviews",
            "/routing/history",
            "/routing/engines",
            "/routing/engines/{engine_name}",
            "/routing/stats",
            "/routing/tasks/{task_id}",
            "/routing/tasks/{task_id}/stats",
            "/goals",
            "/goals/{goal_id}",
            "/goals/{goal_id}/plan",
            "/goals/{goal_id}/timeline",
            "/goals/{goal_id}/status",
            "/goals/{goal_id}/resume",
            "/actions/{action_id}",
            "/actions/{action_id}/retry",
            "/actions/{action_id}/skip",
            "/actions/{action_id}/replace",
            "/goals/{goal_id}/custody",
            "/tasks/{task_id}/custody",
            "/journal",
            "/preferences",
            "/preferences/{preference_type}",
            "/memory",
            "/memory/concepts/extract",
            "/memory/concepts",
            "/memory/concepts/{concept_id}",
            "/memory/concepts/{concept_id}/acknowledge",
            "/memory/development-patterns",
            "/memory/development-patterns/{pattern_id}",
            "/tools",
            "/services",
            "/gateway/intake",
            "/gateway/intake/text",
            "/gateway/intake/ui",
            "/gateway/intake/api",
            "/gateway/events",
            "/gateway/events/{event_id}",
            "/gateway/events/{event_id}/resolution",
            "/gateway/events/{event_id}/promote-to-goal",
            "/gateway/events/{event_id}/execution",
            "/gateway/events/{event_id}/execution/dispatch",
            "/gateway/capabilities/executions/{execution_id}",
            "/gateway/capabilities/executions/{execution_id}/handoff",
            "/gateway/capabilities/executions/{execution_id}/feedback",
            "/gateway/vision-policy",
            "/gateway/voice-policy",
            "/gateway/voice/input",
            "/gateway/voice/output",
            "/gateway/vision/observations",
            "/gateway/perception/camera/events",
            "/gateway/perception/mic/events",
            "/gateway/perception/sources",
            "/gateway/perception/status",
            "/gateway/capabilities",
            "/constraints/evaluate",
            "/constraints/last-evaluation",
            "/constraints/history",
            "/constraints/outcomes",
            "/constraints/learning/stats",
            "/constraints/learning/proposals/generate",
            "/constraints/learning/proposals",
            "/planning/horizon/plans",
            "/planning/horizon/plans/current",
            "/planning/horizon/plans/{plan_id}",
            "/planning/horizon/plans/{plan_id}/checkpoints/advance",
            "/planning/horizon/plans/{plan_id}/future-drift",
            "/planning/strategies/generate",
            "/planning/strategies",
            "/planning/strategies/{strategy_id}",
            "/planning/strategies/{strategy_id}/resolve",
            "/planning/strategies/{strategy_id}/deactivate",
            "/planning/strategies/routines/generate",
            "/planning/decisions",
            "/planning/decisions/{decision_id}",
            "/improvement/proposals/generate",
            "/improvement/proposals",
            "/improvement/proposals/{proposal_id}",
            "/improvement/proposals/{proposal_id}/accept",
            "/improvement/proposals/{proposal_id}/reject",
            "/improvement/experiments/run",
            "/improvement/experiments",
            "/improvement/experiments/{experiment_id}",
            "/improvement/recommendations/generate",
            "/improvement/recommendations",
            "/improvement/recommendations/{recommendation_id}",
            "/improvement/recommendations/{recommendation_id}/approve",
            "/improvement/recommendations/{recommendation_id}/reject",
            "/improvement/backlog/refresh",
            "/improvement/backlog",
            "/improvement/backlog/{improvement_id}",
            "/reasoning/context/build",
            "/reasoning/context",
            "/reasoning/context/{context_id}",
            "/orchestration/build",
            "/orchestration",
            "/orchestration/{orchestration_id}",
            "/orchestration/collaboration/state",
            "/orchestration/collaboration/mode",
            "/collaboration/negotiations",
            "/collaboration/negotiations/{negotiation_id}",
            "/collaboration/negotiations/{negotiation_id}/respond",
            "/collaboration/preferences",
            "/collaboration/patterns",
            "/collaboration/patterns/{pattern_id}",
            "/collaboration/patterns/{pattern_id}/acknowledge",
            "/collaboration/profiles",
            "/collaboration/profiles/{profile_id}",
            "/collaboration/profiles/recompute",
            "/strategy/goals/build",
            "/strategy/goals",
            "/strategy/persistence/goals/recompute",
            "/strategy/persistence/goals",
            "/strategy/goals/{strategy_goal_id}",
            "/strategy/goals/{strategy_goal_id}/review",
            "/strategy/goals/{strategy_goal_id}/reviews",
            "/stewardship/cycle",
            "/stewardship",
            "/stewardship/{stewardship_id}",
            "/stewardship/history",
            "/inquiry/questions",
            "/inquiry/questions/{question_id}",
            "/inquiry/questions/{question_id}/answer",
            "/inquiry/questions/generate",
            "/maintenance/cycle",
            "/maintenance/runs",
            "/maintenance/runs/{run_id}",
            "/operator/inbox",
            "/operator/executions",
            "/operator/executions/{execution_id}",
            "/operator/executions/{execution_id}/approve",
            "/operator/executions/{execution_id}/reject",
            "/operator/executions/{execution_id}/retry",
            "/operator/executions/{execution_id}/resume",
            "/operator/executions/{execution_id}/cancel",
            "/operator/executions/{execution_id}/promote-to-goal",
            "/operator/executions/{execution_id}/observations",
            "/operator/executions/{execution_id}/ignore",
            "/operator/executions/{execution_id}/request-rescan",
            "/workspace/observations",
            "/workspace/observations/{observation_id}",
            "/workspace/objects",
            "/workspace/objects/{object_memory_id}",
            "/workspace/objects/{object_memory_id}/relations",
            "/workspace/map",
            "/workspace/map/zones",
            "/workspace/monitoring",
            "/workspace/monitoring/start",
            "/workspace/monitoring/stop",
            "/workspace/human-aware/state",
            "/workspace/human-aware/signals",
            "/workspace/autonomy/policy",
            "/workspace/autonomy/override",
            "/workspace/autonomy/loop/step",
            "/autonomy/boundaries/recompute",
            "/autonomy/boundaries",
            "/autonomy/boundaries/{boundary_id}",
            "/workspace/autonomy/boundaries/evaluate",
            "/workspace/autonomy/boundaries",
            "/workspace/autonomy/boundaries/{profile_id}",
            "/workspace/chains",
            "/workspace/chains/{chain_id}",
            "/workspace/chains/{chain_id}/approve",
            "/workspace/chains/{chain_id}/audit",
            "/workspace/chains/{chain_id}/advance",
            "/workspace/capability-chains",
            "/workspace/capability-chains/{chain_id}",
            "/workspace/capability-chains/{chain_id}/advance",
            "/workspace/capability-chains/{chain_id}/audit",
            "/workspace/interruptions",
            "/workspace/interruptions/{interruption_id}",
            "/workspace/executions/{execution_id}/pause",
            "/workspace/executions/{execution_id}/resume",
            "/workspace/executions/{execution_id}/stop",
            "/workspace/executions/{execution_id}/predict-change",
            "/workspace/replan-signals",
            "/workspace/replan-signals/{signal_id}",
            "/workspace/proposals",
            "/workspace/proposals/{proposal_id}",
            "/workspace/proposals/{proposal_id}/accept",
            "/workspace/proposals/{proposal_id}/reject",
            "/workspace/proposals/priority-policy",
            "/workspace/proposals/next",
            "/workspace/targets/resolve",
            "/workspace/targets/{target_resolution_id}",
            "/workspace/targets/{target_resolution_id}/confirm",
            "/workspace/action-plans",
            "/workspace/action-plans/{plan_id}",
            "/workspace/action-plans/{plan_id}/approve",
            "/workspace/action-plans/{plan_id}/reject",
            "/workspace/action-plans/{plan_id}/queue",
            "/workspace/action-plans/{plan_id}/simulate",
            "/workspace/action-plans/{plan_id}/simulation",
            "/workspace/action-plans/{plan_id}/replan",
            "/workspace/action-plans/{plan_id}/replan-history",
            "/workspace/action-plans/{plan_id}/execute",
            "/workspace/action-plans/{plan_id}/abort",
            "/workspace/action-plans/{plan_id}/propose-execution",
            "/workspace/execution-proposals/policy",
            "/workspace/execution-proposals",
            "/workspace/execution-proposals/{proposal_id}/accept",
            "/workspace/execution-proposals/{proposal_id}/reject",
            "/state-bus/events",
            "/state-bus/events/{event_id}",
            "/state-bus/snapshots",
            "/state-bus/snapshots/{snapshot_scope}",
            "/state-bus/consumers/{consumer_key}",
            "/state-bus/consumers",
            "/state-bus/consumers/{consumer_key}/poll",
            "/state-bus/consumers/{consumer_key}/ack",
            "/state-bus/consumers/{consumer_key}/replay",
            "/state-bus/consumers/mim-core/step",
            "/state-bus/reactions/mim-tod/step",
        ],
        "objects": {
            "Objective": [
                "objective_id",
                "title",
                "description",
                "priority",
                "constraints",
                "success_criteria",
                "status",
                "created_at",
            ],
            "Task": [
                "task_id",
                "objective_id",
                "title",
                "scope",
                "dependencies",
                "acceptance_criteria",
                "status",
                "assigned_to",
            ],
            "Result": [
                "result_id",
                "task_id",
                "summary",
                "files_changed",
                "tests_run",
                "test_results",
                "failures",
                "recommendations",
                "created_at",
            ],
            "Review": [
                "review_id",
                "task_id",
                "decision",
                "rationale",
                "continue_allowed",
                "escalate_to_user",
                "created_at",
            ],
            "JournalEntry": [
                "entry_id",
                "actor",
                "action",
                "target_type",
                "target_id",
                "summary",
                "timestamp",
            ],
            "Goal": [
                "goal_id",
                "objective_id",
                "task_id",
                "goal_type",
                "goal_description",
                "requested_by",
                "priority",
                "status",
                "created_at",
            ],
            "Action": [
                "action_id",
                "goal_id",
                "engine",
                "action_type",
                "input_ref",
                "expected_state_delta",
                "validation_method",
                "retry_of_action_id",
                "retry_count",
                "replaced_action_id",
                "replacement_action_id",
                "recovery_classification",
                "chain_event",
                "started_at",
                "completed_at",
                "status",
            ],
            "StateSnapshot": [
                "snapshot_id",
                "goal_id",
                "action_id",
                "snapshot_phase",
                "state_type",
                "state_payload",
                "captured_at",
            ],
            "ValidationResult": [
                "validation_id",
                "goal_id",
                "action_id",
                "validation_method",
                "validation_status",
                "validation_details",
                "validated_at",
            ],
            "GoalPlan": [
                "goal_id",
                "ordered_action_ids",
                "current_step_index",
                "derived_status",
            ],
            "InputEvent": [
                "input_id",
                "source",
                "raw_input",
                "parsed_intent",
                "confidence",
                "target_system",
                "requested_goal",
                "safety_flags",
                "metadata_json",
                "normalized",
                "created_at",
            ],
            "CapabilityRegistration": [
                "capability_id",
                "capability_name",
                "category",
                "description",
                "requires_confirmation",
                "enabled",
                "safety_policy",
                "created_at",
            ],
            "InputEventResolution": [
                "resolution_id",
                "input_event_id",
                "internal_intent",
                "confidence_tier",
                "outcome",
                "resolution_status",
                "safety_decision",
                "reason",
                "clarification_prompt",
                "escalation_reasons",
                "capability_name",
                "capability_registered",
                "capability_enabled",
                "goal_id",
                "proposed_goal_description",
                "proposed_actions",
                "metadata_json",
                "created_at",
            ],
            "SpeechOutputAction": [
                "output_action_id",
                "requested_text",
                "voice_profile",
                "channel",
                "priority",
                "delivery_status",
                "failure_reason",
                "metadata_json",
                "created_at",
            ],
            "CapabilityExecution": [
                "execution_id",
                "input_event_id",
                "resolution_id",
                "goal_id",
                "capability_name",
                "arguments_json",
                "safety_mode",
                "requested_executor",
                "dispatch_decision",
                "status",
                "reason",
                "feedback_json",
                "created_at",
            ],
            "WorkspaceObservation": [
                "observation_id",
                "timestamp",
                "zone",
                "detected_object",
                "confidence",
                "effective_confidence",
                "freshness_state",
                "source",
                "related_execution_id",
                "lifecycle_status",
                "observation_count",
                "metadata_json",
            ],
            "WorkspaceObjectMemory": [
                "object_memory_id",
                "canonical_name",
                "aliases",
                "confidence",
                "effective_confidence",
                "zone",
                "first_seen_at",
                "last_seen_at",
                "status",
                "last_execution_id",
                "location_history",
                "metadata_json",
            ],
            "WorkspaceZone": [
                "zone_id",
                "zone_name",
                "display_name",
                "hazard_level",
                "metadata_json",
            ],
            "WorkspaceZoneRelation": [
                "relation_id",
                "from_zone",
                "to_zone",
                "relation_type",
                "confidence",
                "metadata_json",
            ],
            "WorkspaceObjectRelation": [
                "relation_id",
                "subject_object_id",
                "object_object_id",
                "relation_type",
                "relation_status",
                "confidence",
                "last_seen_at",
                "source_execution_id",
                "metadata_json",
            ],
            "WorkspaceProposal": [
                "proposal_id",
                "proposal_type",
                "title",
                "description",
                "status",
                "confidence",
                "priority_score",
                "priority_reason",
                "source",
                "related_zone",
                "related_object_id",
                "source_execution_id",
                "trigger_json",
                "metadata_json",
                "created_at",
            ],
            "UserPreference": [
                "user_id",
                "preference_type",
                "value",
                "confidence",
                "source",
                "last_updated",
            ],
            "WorkspaceInterruptionEvent": [
                "interruption_id",
                "execution_id",
                "action_plan_id",
                "chain_id",
                "interruption_type",
                "source",
                "requested_outcome",
                "applied_outcome",
                "status",
                "reason",
                "actor",
                "resolved_by",
                "resolved_at",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceReplanSignal": [
                "signal_id",
                "execution_id",
                "action_plan_id",
                "chain_id",
                "signal_type",
                "predicted_outcome",
                "confidence",
                "source",
                "status",
                "reason",
                "actor",
                "resolved_by",
                "resolved_at",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceTargetResolution": [
                "target_resolution_id",
                "requested_target",
                "requested_zone",
                "match_outcome",
                "policy_outcome",
                "status",
                "confidence",
                "related_object_id",
                "candidate_object_ids",
                "suggested_actions",
                "source",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceActionPlan": [
                "plan_id",
                "target_resolution_id",
                "target_label",
                "target_zone",
                "action_type",
                "safety_mode",
                "planning_outcome",
                "status",
                "steps",
                "motion_plan",
                "simulation_outcome",
                "simulation_status",
                "simulation",
                "simulation_gate_passed",
                "execution_capability",
                "execution_status",
                "execution_id",
                "execution",
                "abort_status",
                "abort_reason",
                "queued_task_id",
                "source",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceMonitoringState": [
                "desired_running",
                "runtime_status",
                "policy",
                "last_scan_at",
                "scan_count",
                "last_scan_reason",
                "last_deltas",
                "last_proposal_ids",
                "last_started_at",
                "last_stopped_at",
                "metadata_json",
            ],
            "WorkspaceAutonomousChain": [
                "id",
                "chain_type",
                "status",
                "source",
                "trigger_reason",
                "step_proposal_ids",
                "step_policy_json",
                "stop_on_failure",
                "cooldown_seconds",
                "requires_approval",
                "approved_by",
                "approved_at",
                "last_advanced_at",
                "current_step_index",
                "completed_step_ids",
                "failed_step_ids",
                "audit_trail_json",
                "metadata_json",
                "created_at",
            ],
            "ConstraintEvaluation": [
                "evaluation_id",
                "source",
                "actor",
                "decision",
                "violations",
                "warnings",
                "recommended_next_step",
                "confidence",
                "goal",
                "action_plan",
                "workspace_state",
                "system_state",
                "policy_state",
                "outcome_result",
                "outcome_quality",
                "outcome_recorded_at",
                "explanation",
                "created_at",
            ],
            "ConstraintAdjustmentProposal": [
                "proposal_id",
                "source",
                "actor",
                "constraint_key",
                "proposal_type",
                "current_value",
                "proposed_value",
                "sample_size",
                "success_rate",
                "hard_constraint",
                "rationale",
                "status",
                "metadata_json",
                "created_at",
            ],
            "HorizonPlan": [
                "plan_id",
                "actor",
                "source",
                "status",
                "planning_horizon_minutes",
                "ranked_goals",
                "staged_action_graph",
                "expected_future_constraints",
                "scoring_context",
                "explanation",
                "checkpoints",
                "next_checkpoint",
                "metadata_json",
                "created_at",
            ],
            "EnvironmentStrategy": [
                "strategy_id",
                "source",
                "strategy_type",
                "target_scope",
                "priority",
                "current_status",
                "success_criteria",
                "contributing_goals",
                "contributing_checkpoints",
                "status_reason",
                "evidence",
                "influence_weight",
                "influenced_plan_ids",
                "metadata_json",
                "created_at",
            ],
            "DecisionRecord": [
                "decision_id",
                "decision_type",
                "source_context",
                "relevant_state",
                "preferences_applied",
                "constraints_applied",
                "strategies_applied",
                "options_considered",
                "selected_option",
                "decision_reason",
                "confidence",
                "result_quality",
                "resulting_goal_or_plan_id",
                "metadata_json",
                "created_at",
            ],
            "ImprovementProposal": [
                "proposal_id",
                "source",
                "actor",
                "proposal_type",
                "trigger_pattern",
                "evidence_summary",
                "evidence",
                "affected_component",
                "suggested_change",
                "confidence",
                "safety_class",
                "risk_summary",
                "test_recommendation",
                "status",
                "review_reason",
                "metadata_json",
                "created_at",
            ],
            "ImprovementArtifact": [
                "artifact_id",
                "proposal_id",
                "artifact_type",
                "status",
                "candidate_payload",
                "metadata_json",
                "created_at",
            ],
            "MaintenanceRun": [
                "run_id",
                "source",
                "actor",
                "status",
                "detected_signals",
                "created_strategy_ids",
                "executed_action_ids",
                "maintenance_outcomes",
                "stabilized",
                "metadata_json",
                "created_at",
            ],
            "MaintenanceAction": [
                "action_id",
                "run_id",
                "strategy_id",
                "action_type",
                "target_scope",
                "safety_mode",
                "status",
                "reason",
                "details_json",
                "created_at",
            ],
            "PolicyExperiment": [
                "experiment_id",
                "source",
                "actor",
                "proposal_id",
                "experiment_type",
                "sandbox_mode",
                "status",
                "baseline_metrics",
                "experimental_metrics",
                "comparison",
                "recommendation",
                "recommendation_reason",
                "metadata_json",
                "created_at",
            ],
            "ConceptMemory": [
                "concept_id",
                "source",
                "actor",
                "concept_type",
                "trigger_pattern",
                "evidence_count",
                "confidence",
                "affected_zones",
                "affected_objects",
                "affected_strategies",
                "suggested_implications",
                "evidence_summary",
                "status",
                "acknowledged_by",
                "acknowledged_at",
                "metadata_json",
                "created_at",
            ],
            "DevelopmentPattern": [
                "pattern_id",
                "source",
                "actor",
                "pattern_type",
                "evidence_count",
                "confidence",
                "affected_component",
                "first_seen",
                "last_seen",
                "evidence_summary",
                "status",
                "metadata_json",
                "created_at",
            ],
            "ImprovementRecommendation": [
                "recommendation_id",
                "source",
                "actor",
                "proposal_id",
                "experiment_id",
                "recommendation_type",
                "recommendation_summary",
                "baseline_metrics",
                "experimental_metrics",
                "comparison",
                "status",
                "review_reason",
                "reviewed_by",
                "reviewed_at",
                "metadata_json",
                "created_at",
                "latest_artifact",
            ],
            "ImprovementBacklogItem": [
                "improvement_id",
                "proposal_id",
                "recommendation_id",
                "priority_score",
                "proposal_type",
                "evidence_count",
                "risk_level",
                "impact_estimate",
                "evidence_strength",
                "affected_capabilities",
                "operator_preference_weight",
                "governance_decision",
                "status",
                "why_ranked",
                "evidence_summary",
                "risk_summary",
                "reasoning",
                "metadata_json",
                "created_at",
            ],
            "CrossDomainReasoningContext": [
                "context_id",
                "source",
                "actor",
                "lookback_hours",
                "workspace_state",
                "communication_state",
                "external_information",
                "development_state",
                "self_improvement_state",
                "reasoning_summary",
                "reasoning",
                "confidence",
                "status",
                "metadata_json",
                "created_at",
            ],
            "StrategyGoal": [
                "strategy_goal_id",
                "source",
                "actor",
                "strategy_type",
                "origin_context_id",
                "priority",
                "priority_score",
                "success_criteria",
                "status",
                "evidence_summary",
                "supporting_evidence",
                "contributing_domains",
                "ranking_factors",
                "reasoning_summary",
                "reasoning",
                "linked_horizon_plan_ids",
                "linked_improvement_proposal_ids",
                "linked_maintenance_run_ids",
                "operator_recommendations",
                "persistence_state",
                "review_status",
                "persistence_confidence",
                "surviving_sessions",
                "carry_forward_count",
                "last_reviewed_at",
                "review_notes",
                "metadata_json",
                "created_at",
            ],
            "StrategyGoalReview": [
                "review_id",
                "strategy_goal_id",
                "actor",
                "decision",
                "reason",
                "resulting_persistence_state",
                "resulting_review_status",
                "evidence_json",
                "metadata_json",
                "created_at",
            ],
            "AdaptiveAutonomyBoundaryProfile": [
                "boundary_id",
                "profile_id",
                "scope",
                "source",
                "actor",
                "profile_status",
                "current_level",
                "confidence",
                "evidence_inputs",
                "last_adjusted",
                "adjustment_reason",
                "lookback_hours",
                "sample_count",
                "success_rate",
                "escalation_rate",
                "retry_rate",
                "interruption_rate",
                "memory_delta_rate",
                "current_boundaries",
                "recommended_boundaries",
                "applied_boundaries",
                "adaptation_summary",
                "adaptation_reasoning",
                "metadata_json",
                "created_at",
            ],
            "Stewardship": [
                "stewardship_id",
                "source",
                "actor",
                "status",
                "target_environment_state",
                "managed_scope",
                "maintenance_priority",
                "current_health",
                "last_cycle",
                "next_cycle",
                "cycle_count",
                "linked_strategy_goal_ids",
                "linked_maintenance_run_ids",
                "linked_strategy_types",
                "linked_autonomy_boundary_id",
                "last_decision_summary",
                "metadata_json",
                "created_at",
            ],
            "StewardshipCycle": [
                "cycle_id",
                "stewardship_id",
                "source",
                "actor",
                "pre_health",
                "post_health",
                "improvement_delta",
                "degraded_signals",
                "selected_actions",
                "decision",
                "integration_evidence",
                "maintenance_run_id",
                "improved",
                "metadata_json",
                "created_at",
            ],
            "PerceptionSourceStatus": [
                "source_id",
                "source_type",
                "device_id",
                "session_id",
                "is_remote",
                "status",
                "health_status",
                "last_seen_at",
                "last_accepted_at",
                "accepted_count",
                "dropped_count",
                "duplicate_count",
                "low_confidence_count",
                "min_interval_seconds",
                "duplicate_window_seconds",
                "confidence_floor",
                "metadata_json",
                "created_at",
            ],
            "InquiryQuestion": [
                "question_id",
                "source",
                "actor",
                "status",
                "trigger_type",
                "uncertainty_type",
                "originating_goal_id",
                "originating_strategy_id",
                "originating_plan_id",
                "why_answer_matters",
                "waiting_decision",
                "no_answer_behavior",
                "candidate_answer_paths",
                "urgency",
                "priority",
                "safe_default_if_unanswered",
                "trigger_evidence",
                "selected_path_id",
                "answer_json",
                "applied_effect_json",
                "answered_by",
                "answered_at",
                "metadata_json",
                "created_at",
            ],
            "CollaborationPattern": [
                "pattern_id",
                "source",
                "actor",
                "pattern_type",
                "context_signature",
                "evidence_count",
                "confidence",
                "dominant_outcome",
                "affected_domains",
                "status",
                "evidence_summary",
                "explainability",
                "influence_profile",
                "acknowledged_by",
                "acknowledged_at",
                "last_observed_at",
                "metadata_json",
                "created_at",
            ],
            "CollaborationProfile": [
                "profile_id",
                "source",
                "actor",
                "profile_type",
                "context_scope",
                "dominant_collaboration_mode",
                "supporting_pattern_ids",
                "evidence_count",
                "confidence",
                "freshness",
                "status",
                "evidence_summary",
                "explainability",
                "influence_profile",
                "last_observed_at",
                "metadata_json",
                "created_at",
            ],
            "StateBusEvent": [
                "event_id",
                "source",
                "actor",
                "event_domain",
                "event_type",
                "stream_key",
                "sequence_id",
                "occurred_at",
                "payload_json",
                "metadata_json",
                "created_at",
            ],
            "StateBusSnapshot": [
                "snapshot_id",
                "source",
                "actor",
                "snapshot_scope",
                "state_version",
                "state_payload_json",
                "last_event_id",
                "last_event_sequence",
                "last_event_domain",
                "last_event_type",
                "metadata_json",
                "updated_at",
                "created_at",
            ],
            "StateBusConsumer": [
                "consumer_id",
                "source",
                "actor",
                "consumer_key",
                "status",
                "subscription",
                "cursor_event_id",
                "cursor_occurred_at",
                "processed_event_ids",
                "poll_count",
                "ack_count",
                "lag_count",
                "replay_from_snapshot_scope",
                "last_polled_at",
                "last_acked_at",
                "last_replayed_at",
                "metadata_json",
                "updated_at",
                "created_at",
            ],
        },
    }
