from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path
import subprocess

from core.config import PROJECT_ROOT, settings

CONTRACT_VERSION = "tod-mim-shared-contract-v1"
MANIFEST_VERSION = "1"
SCHEMA_VERSION = "2026-03-10-29"

SIGNATURE_FILES = [
    "core/models.py",
    "core/schemas.py",
    "core/routers/__init__.py",
    "core/routers/gateway.py",
    "core/vision_policy.py",
    "core/voice_policy.py",
    "core/routers/manifest.py",
    "core/config.py",
    "core/manifest.py",
    "docs/tod-mim-bridge.md",
    "docs/objective-21-unified-input-gateway.md",
    "docs/objective-22-mim-tod-execution-feedback-integration.md",
    "docs/objective-23-operator-control-and-exception-handling.md",
    "docs/objective-23b-safe-capability-expansion.md",
    "docs/objective-24-workspace-observation-memory.md",
    "docs/objective-25-memory-informed-routing.md",
    "docs/objective-26-object-identity-persistence.md",
    "docs/objective-27-workspace-map-and-relational-context.md",
    "docs/objective-28-autonomous-task-proposals.md",
    "docs/objective-29-directed-targeting.md",
    "docs/objective-30-safe-directed-action-planning.md",
    "docs/objective-31-safe-reach-approach-simulation.md",
    "docs/objective-32-safe-reach-execution.md",
    "docs/objective-33-autonomous-execution-proposals.md",
    "docs/objective-34-continuous-workspace-monitoring-loop.md",
    "docs/objective-35-autonomous-task-execution-policies.md",
    "docs/objective-36-multi-step-autonomous-task-chaining.md",
    "docs/objective-37-human-aware-interruption-and-safe-pause-handling.md",
    "docs/objective-38-predictive-workspace-change-and-replanning.md",
    "core/routers/workspace.py",
    "config/vision_policy.json",
    "config/voice_policy.json",
]

CAPABILITIES = [
    "health",
    "status",
    "manifest",
    "objectives",
    "tasks",
    "results",
    "reviews",
    "journal",
    "routing_history",
    "routing_engines",
    "routing_stats",
    "routing_engine_detail",
    "routing_task_stats",
    "goals",
    "actions",
    "custody_chain",
    "goal_plans",
    "goal_timeline",
    "goal_status",
    "goal_recovery",
    "unified_input_gateway",
    "speech_output",
    "speech_input_adapter",
    "vision_observation_adapter",
    "capability_registry",
    "capability_to_goal_bridge",
    "event_resolution",
    "vision_confidence_policy",
    "voice_confidence_policy",
    "speech_output_execution",
    "capability_execution_binding",
    "execution_feedback_updater",
    "execution_handoff_contract",
    "tod_feedback_publisher",
    "execution_feedback_auth_boundary",
    "operator_execution_inbox",
    "operator_execution_actions",
    "operator_exception_normalization",
    "workspace_scan_capability",
    "operator_observation_review",
    "workspace_observation_memory",
    "workspace_observation_query_api",
    "memory_informed_routing",
    "object_identity_persistence",
    "workspace_map_relational_context",
    "autonomous_workspace_task_proposals",
    "directed_workspace_targeting",
    "safe_directed_action_planning",
    "safe_reach_approach_simulation",
    "safe_reach_execution",
    "autonomous_execution_proposals",
    "continuous_workspace_monitoring_loop",
    "autonomous_task_execution_policies",
    "multi_step_autonomous_task_chaining",
    "human_aware_interruption_pause_handling",
    "predictive_workspace_change_replanning",
]

RECENT_CHANGES = [
    "Added review endpoint",
    "Added journal endpoint",
    "Aligned structured workflow schema",
    "Added manifest endpoint and metadata",
    "Added goal/action/state/validation custody chain",
    "Added multi-step goal execution planning and timeline/status endpoints",
    "Added retry/skip/replace/resume recovery operations for goal chains",
    "Added Objective 21 unified input gateway and adapters",
    "Added Objective 21.2 capability-to-goal bridge with safety gating and inspectability",
    "Added Objective 21.3 vision observation confidence policy tiers and escalation outcomes",
    "Added runtime vision policy inspection endpoint",
    "Added Objective 21.4 voice interaction policy and structured speech output execution",
    "Added Objective 21.5 capability execution binding and dispatch inspectability",
    "Added Objective 21.7 guarded execution feedback updater",
    "Added Objective 22 MIM↔TOD execution handoff contract and feedback integration",
    "Added Objective 23 operator control surface and exception handling endpoints",
    "Added Objective 23B safe capability expansion for workspace_scan",
    "Added Objective 24 workspace observation memory with dedupe, aging, and query endpoints",
    "Added Objective 25 memory-informed routing from workspace observation memory",
    "Added Objective 26 object identity persistence with matching and moved/missing logic",
    "Added Objective 27 workspace map and relational context with spatial routing hints",
    "Added Objective 28 autonomous workspace-state task proposals and operator review actions",
    "Added Objective 29 directed workspace target resolution with confidence policy and confirmation",
    "Added Objective 30 safe directed action planning with operator approval and queue handoff",
    "Added Objective 31 safe reach/approach simulation with collision policy and queue gating",
    "Added Objective 32 safe reach execution with precondition gating and abort controls",
    "Added Objective 33 autonomous execution proposals with policy endpoints and operator acceptance",
    "Added Objective 34 continuous workspace monitoring loop with delta-driven proposal triggers",
    "Added Objective 35 autonomous task execution policies with safety-throttled auto-execution and operator overrides",
    "Added Objective 36 policy-controlled multi-step autonomous task chaining with approval/cooldown/failure controls and chain audit trail",
    "Added Objective 37 human-aware interruption events with policy-driven pause/stop/resume controls and safety-validated resume gating",
    "Added Objective 38 predictive workspace-change signaling and preemptive action-plan replanning workflow",
]


def _signature_input() -> str:
    blocks: list[str] = [
        f"contract_version={CONTRACT_VERSION}",
        f"schema_version={SCHEMA_VERSION}",
    ]

    for rel_path in SIGNATURE_FILES:
        file_path = PROJECT_ROOT / rel_path
        if file_path.exists():
            content_hash = sha256(file_path.read_bytes()).hexdigest()
            blocks.append(f"{rel_path}:{content_hash}")
        else:
            blocks.append(f"{rel_path}:missing")

    return "\n".join(blocks)


def _last_updated_at() -> datetime:
    timestamps: list[float] = []
    for rel_path in SIGNATURE_FILES:
        file_path = PROJECT_ROOT / rel_path
        if file_path.exists():
            timestamps.append(file_path.stat().st_mtime)

    if not timestamps:
        return datetime.now(timezone.utc)

    return datetime.fromtimestamp(max(timestamps), tz=timezone.utc)


def build_repo_signature() -> str:
    seed = _signature_input()
    return f"sha256:{sha256(seed.encode('utf-8')).hexdigest()}"


def _resolve_git_sha() -> str:
    if settings.build_git_sha and settings.build_git_sha != "unknown":
        return settings.build_git_sha

    try:
        result = subprocess.run(
            ["git", "-C", str(PROJECT_ROOT), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"


def build_manifest() -> dict:
    return {
        "system_name": "MIM",
        "system_version": settings.app_version,
        "manifest_version": MANIFEST_VERSION,
        "contract_version": CONTRACT_VERSION,
        "schema_version": SCHEMA_VERSION,
        "app_name": settings.app_name,
        "app_version": settings.app_version,
        "environment": settings.environment,
        "release_tag": settings.release_tag,
        "config_profile": settings.config_profile,
        "git_sha": _resolve_git_sha(),
        "build_timestamp": settings.build_timestamp,
        "repo_signature": build_repo_signature(),
        "capabilities": CAPABILITIES,
        "recent_changes": RECENT_CHANGES,
        "last_updated_at": _last_updated_at(),
        "generated_at": datetime.now(timezone.utc),
        "endpoints": [
            "/health",
            "/status",
            "/manifest",
            "/objectives",
            "/tasks",
            "/results",
            "/reviews",
            "/routing/history",
            "/routing/engines",
            "/routing/engines/{engine_name}",
            "/routing/stats",
            "/routing/tasks/{task_id}",
            "/routing/tasks/{task_id}/stats",
            "/goals",
            "/goals/{goal_id}",
            "/goals/{goal_id}/plan",
            "/goals/{goal_id}/timeline",
            "/goals/{goal_id}/status",
            "/goals/{goal_id}/resume",
            "/actions/{action_id}",
            "/actions/{action_id}/retry",
            "/actions/{action_id}/skip",
            "/actions/{action_id}/replace",
            "/goals/{goal_id}/custody",
            "/tasks/{task_id}/custody",
            "/journal",
            "/memory",
            "/tools",
            "/services",
            "/gateway/intake",
            "/gateway/intake/text",
            "/gateway/intake/ui",
            "/gateway/intake/api",
            "/gateway/events",
            "/gateway/events/{event_id}",
            "/gateway/events/{event_id}/resolution",
            "/gateway/events/{event_id}/promote-to-goal",
            "/gateway/events/{event_id}/execution",
            "/gateway/events/{event_id}/execution/dispatch",
            "/gateway/capabilities/executions/{execution_id}",
            "/gateway/capabilities/executions/{execution_id}/handoff",
            "/gateway/capabilities/executions/{execution_id}/feedback",
            "/gateway/vision-policy",
            "/gateway/voice-policy",
            "/gateway/voice/input",
            "/gateway/voice/output",
            "/gateway/vision/observations",
            "/gateway/capabilities",
            "/operator/inbox",
            "/operator/executions",
            "/operator/executions/{execution_id}",
            "/operator/executions/{execution_id}/approve",
            "/operator/executions/{execution_id}/reject",
            "/operator/executions/{execution_id}/retry",
            "/operator/executions/{execution_id}/resume",
            "/operator/executions/{execution_id}/cancel",
            "/operator/executions/{execution_id}/promote-to-goal",
            "/operator/executions/{execution_id}/observations",
            "/operator/executions/{execution_id}/ignore",
            "/operator/executions/{execution_id}/request-rescan",
            "/workspace/observations",
            "/workspace/observations/{observation_id}",
            "/workspace/objects",
            "/workspace/objects/{object_memory_id}",
            "/workspace/objects/{object_memory_id}/relations",
            "/workspace/map",
            "/workspace/map/zones",
            "/workspace/monitoring",
            "/workspace/monitoring/start",
            "/workspace/monitoring/stop",
            "/workspace/autonomy/policy",
            "/workspace/autonomy/override",
            "/workspace/chains",
            "/workspace/chains/{chain_id}",
            "/workspace/chains/{chain_id}/approve",
            "/workspace/chains/{chain_id}/audit",
            "/workspace/chains/{chain_id}/advance",
            "/workspace/interruptions",
            "/workspace/interruptions/{interruption_id}",
            "/workspace/executions/{execution_id}/pause",
            "/workspace/executions/{execution_id}/resume",
            "/workspace/executions/{execution_id}/stop",
            "/workspace/executions/{execution_id}/predict-change",
            "/workspace/replan-signals",
            "/workspace/replan-signals/{signal_id}",
            "/workspace/proposals",
            "/workspace/proposals/{proposal_id}",
            "/workspace/proposals/{proposal_id}/accept",
            "/workspace/proposals/{proposal_id}/reject",
            "/workspace/targets/resolve",
            "/workspace/targets/{target_resolution_id}",
            "/workspace/targets/{target_resolution_id}/confirm",
            "/workspace/action-plans",
            "/workspace/action-plans/{plan_id}",
            "/workspace/action-plans/{plan_id}/approve",
            "/workspace/action-plans/{plan_id}/reject",
            "/workspace/action-plans/{plan_id}/queue",
            "/workspace/action-plans/{plan_id}/simulate",
            "/workspace/action-plans/{plan_id}/simulation",
            "/workspace/action-plans/{plan_id}/replan",
            "/workspace/action-plans/{plan_id}/replan-history",
            "/workspace/action-plans/{plan_id}/execute",
            "/workspace/action-plans/{plan_id}/abort",
            "/workspace/action-plans/{plan_id}/propose-execution",
            "/workspace/execution-proposals/policy",
            "/workspace/execution-proposals",
            "/workspace/execution-proposals/{proposal_id}/accept",
            "/workspace/execution-proposals/{proposal_id}/reject",
        ],
        "objects": {
            "Objective": [
                "objective_id",
                "title",
                "description",
                "priority",
                "constraints",
                "success_criteria",
                "status",
                "created_at",
            ],
            "Task": [
                "task_id",
                "objective_id",
                "title",
                "scope",
                "dependencies",
                "acceptance_criteria",
                "status",
                "assigned_to",
            ],
            "Result": [
                "result_id",
                "task_id",
                "summary",
                "files_changed",
                "tests_run",
                "test_results",
                "failures",
                "recommendations",
                "created_at",
            ],
            "Review": [
                "review_id",
                "task_id",
                "decision",
                "rationale",
                "continue_allowed",
                "escalate_to_user",
                "created_at",
            ],
            "JournalEntry": [
                "entry_id",
                "actor",
                "action",
                "target_type",
                "target_id",
                "summary",
                "timestamp",
            ],
            "Goal": [
                "goal_id",
                "objective_id",
                "task_id",
                "goal_type",
                "goal_description",
                "requested_by",
                "priority",
                "status",
                "created_at",
            ],
            "Action": [
                "action_id",
                "goal_id",
                "engine",
                "action_type",
                "input_ref",
                "expected_state_delta",
                "validation_method",
                "retry_of_action_id",
                "retry_count",
                "replaced_action_id",
                "replacement_action_id",
                "recovery_classification",
                "chain_event",
                "started_at",
                "completed_at",
                "status",
            ],
            "StateSnapshot": [
                "snapshot_id",
                "goal_id",
                "action_id",
                "snapshot_phase",
                "state_type",
                "state_payload",
                "captured_at",
            ],
            "ValidationResult": [
                "validation_id",
                "goal_id",
                "action_id",
                "validation_method",
                "validation_status",
                "validation_details",
                "validated_at",
            ],
            "GoalPlan": [
                "goal_id",
                "ordered_action_ids",
                "current_step_index",
                "derived_status",
            ],
            "InputEvent": [
                "input_id",
                "source",
                "raw_input",
                "parsed_intent",
                "confidence",
                "target_system",
                "requested_goal",
                "safety_flags",
                "metadata_json",
                "normalized",
                "created_at",
            ],
            "CapabilityRegistration": [
                "capability_id",
                "capability_name",
                "category",
                "description",
                "requires_confirmation",
                "enabled",
                "safety_policy",
                "created_at",
            ],
            "InputEventResolution": [
                "resolution_id",
                "input_event_id",
                "internal_intent",
                "confidence_tier",
                "outcome",
                "resolution_status",
                "safety_decision",
                "reason",
                "clarification_prompt",
                "escalation_reasons",
                "capability_name",
                "capability_registered",
                "capability_enabled",
                "goal_id",
                "proposed_goal_description",
                "proposed_actions",
                "metadata_json",
                "created_at",
            ],
            "SpeechOutputAction": [
                "output_action_id",
                "requested_text",
                "voice_profile",
                "channel",
                "priority",
                "delivery_status",
                "failure_reason",
                "metadata_json",
                "created_at",
            ],
            "CapabilityExecution": [
                "execution_id",
                "input_event_id",
                "resolution_id",
                "goal_id",
                "capability_name",
                "arguments_json",
                "safety_mode",
                "requested_executor",
                "dispatch_decision",
                "status",
                "reason",
                "feedback_json",
                "created_at",
            ],
            "WorkspaceObservation": [
                "observation_id",
                "timestamp",
                "zone",
                "detected_object",
                "confidence",
                "effective_confidence",
                "freshness_state",
                "source",
                "related_execution_id",
                "lifecycle_status",
                "observation_count",
                "metadata_json",
            ],
            "WorkspaceObjectMemory": [
                "object_memory_id",
                "canonical_name",
                "aliases",
                "confidence",
                "effective_confidence",
                "zone",
                "first_seen_at",
                "last_seen_at",
                "status",
                "last_execution_id",
                "location_history",
                "metadata_json",
            ],
            "WorkspaceZone": [
                "zone_id",
                "zone_name",
                "display_name",
                "hazard_level",
                "metadata_json",
            ],
            "WorkspaceZoneRelation": [
                "relation_id",
                "from_zone",
                "to_zone",
                "relation_type",
                "confidence",
                "metadata_json",
            ],
            "WorkspaceObjectRelation": [
                "relation_id",
                "subject_object_id",
                "object_object_id",
                "relation_type",
                "relation_status",
                "confidence",
                "last_seen_at",
                "source_execution_id",
                "metadata_json",
            ],
            "WorkspaceProposal": [
                "proposal_id",
                "proposal_type",
                "title",
                "description",
                "status",
                "confidence",
                "source",
                "related_zone",
                "related_object_id",
                "source_execution_id",
                "trigger_json",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceInterruptionEvent": [
                "interruption_id",
                "execution_id",
                "action_plan_id",
                "chain_id",
                "interruption_type",
                "source",
                "requested_outcome",
                "applied_outcome",
                "status",
                "reason",
                "actor",
                "resolved_by",
                "resolved_at",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceReplanSignal": [
                "signal_id",
                "execution_id",
                "action_plan_id",
                "chain_id",
                "signal_type",
                "predicted_outcome",
                "confidence",
                "source",
                "status",
                "reason",
                "actor",
                "resolved_by",
                "resolved_at",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceTargetResolution": [
                "target_resolution_id",
                "requested_target",
                "requested_zone",
                "match_outcome",
                "policy_outcome",
                "status",
                "confidence",
                "related_object_id",
                "candidate_object_ids",
                "suggested_actions",
                "source",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceActionPlan": [
                "plan_id",
                "target_resolution_id",
                "target_label",
                "target_zone",
                "action_type",
                "safety_mode",
                "planning_outcome",
                "status",
                "steps",
                "motion_plan",
                "simulation_outcome",
                "simulation_status",
                "simulation",
                "simulation_gate_passed",
                "execution_capability",
                "execution_status",
                "execution_id",
                "execution",
                "abort_status",
                "abort_reason",
                "queued_task_id",
                "source",
                "metadata_json",
                "created_at",
            ],
            "WorkspaceMonitoringState": [
                "desired_running",
                "runtime_status",
                "policy",
                "last_scan_at",
                "scan_count",
                "last_scan_reason",
                "last_deltas",
                "last_proposal_ids",
                "last_started_at",
                "last_stopped_at",
                "metadata_json",
            ],
            "WorkspaceAutonomousChain": [
                "id",
                "chain_type",
                "status",
                "source",
                "trigger_reason",
                "step_proposal_ids",
                "step_policy_json",
                "stop_on_failure",
                "cooldown_seconds",
                "requires_approval",
                "approved_by",
                "approved_at",
                "last_advanced_at",
                "current_step_index",
                "completed_step_ids",
                "failed_step_ids",
                "audit_trail_json",
                "metadata_json",
                "created_at",
            ],
        },
    }
