from fastapi import APIRouter

from core.routers import constraint_learning, constraints, custody, decision_records, environment_strategy, gateway, health, horizon_planning, improvement, journal, maintenance, manifest, memory, objectives, operator, policy_experiments, preferences, results, reviews, routing, services, status, tasks, tools, workspace

api_router = APIRouter()
api_router.include_router(health.router, prefix="")
api_router.include_router(status.router, prefix="")
api_router.include_router(manifest.router, prefix="")
api_router.include_router(gateway.router, prefix="/gateway", tags=["gateway"])
api_router.include_router(operator.router, prefix="/operator", tags=["operator"])
api_router.include_router(objectives.router, prefix="/objectives", tags=["objectives"])
api_router.include_router(tasks.router, prefix="/tasks", tags=["tasks"])
api_router.include_router(custody.router, prefix="", tags=["custody"])
api_router.include_router(results.router, prefix="/results", tags=["results"])
api_router.include_router(reviews.router, prefix="/reviews", tags=["reviews"])
api_router.include_router(routing.router, prefix="/routing", tags=["routing"])
api_router.include_router(journal.router, prefix="/journal", tags=["journal"])
api_router.include_router(memory.router, prefix="/memory", tags=["memory"])
api_router.include_router(constraints.router, prefix="", tags=["constraints"])
api_router.include_router(constraint_learning.router, prefix="", tags=["constraints-learning"])
api_router.include_router(horizon_planning.router, prefix="", tags=["planning-horizon"])
api_router.include_router(environment_strategy.router, prefix="", tags=["planning-strategy"])
api_router.include_router(decision_records.router, prefix="", tags=["planning-decisions"])
api_router.include_router(improvement.router, prefix="", tags=["improvement"])
api_router.include_router(policy_experiments.router, prefix="", tags=["improvement"])
api_router.include_router(maintenance.router, prefix="", tags=["maintenance"])
api_router.include_router(preferences.router, prefix="", tags=["preferences"])
api_router.include_router(workspace.router, prefix="/workspace", tags=["workspace"])
api_router.include_router(tools.router, prefix="/tools", tags=["tools"])
api_router.include_router(services.router, prefix="/services", tags=["services"])
